Add metadata update ceremony (#284)
* Bootstrap: assert that roles expiry is >= 1 day

Add a check that the roles expiry is at least a day.
This check is meaningfull to assure that zero and negative values
are not accepted as it's possible to use a negative amount of days
in timedelta when calculating the result expiry for a given role.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Ceremony: small refactoring as preparation

This will be useful for the metadata update function.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Add metadata update ceremony

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Small text fixes based on suggestions

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Remove expiration changes for all except root

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Make current-root-uri optional, but ask for value

The user can now call "rstuf admin metadata update" without providing
directly the "current-root-uri", but will be asked about this.
This way if there are users who didn't understand the
"current-root-uri" option can use it.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* If no checks are made file won't be generated

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Address comments

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Add a notice about md update as alpha feature

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Remove unnecessary root string from table

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Enable fetching root.json from URL

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Fix linting

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Fix import problems

When trying to run any of the modules in repository_service_tuf/helpers
I got this error:

"ImportError: cannot import name 'URL' from partially initialized module
'repository_service_tuf.helpers.api_client'
(most likely due to a circular import) (
repository_service_tuf/helpers/api_client.py)"

This problem comes from loading all modules when importing
repository_service_tuf/cli/__init__.py which loads all modules creating
a circular import.
The fix is to not import anything in the helper modules from
'repository_service_tuf/cli/__init__.py'.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Revert a change I made causing tests staling

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Move `_load_key` to a public function in `helpers`

Make `_load_key` a public function which can be used from elsewhere
besides the ceremony module.
The `load_key` is now part of `helpers.tuf` and can be used for a
generic key loading file.

Signed-off-by: Kairo de Araujo <kdearaujo@vmware.com>

* Move save_payload as a helper function

This is done, so it's logical when it's reused by other commands besides
the bootstrap ceremony.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Linting fixes

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Metadata rotation: add step number prefix

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Move load_bootstrap_payload as a helper function

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Make _send_bootstrap a helper function

This will help other ceremonies (such as the metadata update ceremony)
to be able to reuse the _send_bootstrap function.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Allow uploading of the metadata update payload

Allow users to directly upload existing metadata update payload file to
a repository or run the whole metadata update ceremony and then upload
it.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Fix linting

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Use upper case for column names to be consistent

Use upper case for column names to be consistent with the metadata
update ceremony naming.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Metadata update: add documentation

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Move get_current_root as a helper function

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Fix wording and unnecery check based on feedback

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Update ceremony doc

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Add unit tests and do some lint fixes

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Forbid keys with empty string name and test that

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Rename step to "modify root keys"

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Fix prompt causing error and color prompts

Also color the bootstrap ceremony key password prompt to achieve
consistency.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Fix small findings found during testing

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Improve signing keys handling

There is a problem in the implementation until now that while we check
if we have enough singing keys when the users want to stop adding keys
in "_keys_additions" then we check the number of keys against
threshold without taking into account that not all of those keys are
loaded. This means they cannot be used for signing and the check is
wrong.

I also improved generate_payload in order to make it clearer with which
keys we do sign at which stage.

Finally, I improved the documentation for the user, so that it's clear
that when a user considers if he wants to add a key he must take into account
the loaded keys that he can use for signing and not all of the root
keys.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Update docs

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Add full integration tests

I have also added a static root.json in order to simulate as much as
possible a real environment.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Fix unit test mocking leakage causing problems

When we mock an imported object in a test directly with pretend
this changes this object for all other test functions that want to use
it because top-level imports happen in the begging of the testing phase
before any test is run and they won't be reimported.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Follow style guideliness and rename file and tests

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Hardcode POST method to send_payload as suggested

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Use one container for root signing keys

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Use RSTUFKey instances only for signing keys

It could lead to confusion when we use RSTUF key instances for
non-signing keys and that's why I figure out a way how to handle this.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Address feedback on smaller comments

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Simplify get_md_file api helper

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* If if expiration has expired don't ask the user

If expiration has expired, then don't ask the user if he wants to
change it. Just ask him how many days he wants to change it.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* If the threshold is not met, don't ask the user

If the threshold requirement is not met and the user says he doesn't
want to add a key, then tell him that the threshold requirement is not
met and ask him again for a new key.
Don't give him the opportunity to abort the procedure as this will
throw an exception in this case and doesn't bring any value.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Fix linting

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Apply smaller feedback suggestions

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Don't add key names if the user doesn't give one

Stop adding names to the keys when the user doesn't want to.
This will make sure that root metadata is not changed if the user
doesn't want to.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Don't use RSTUFKey for online key

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Improve verification of signatures

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Small Renames

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Rename "current_root" -> "root_info"

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Once added don't remove a key from signing_keys

There is a requirement from the specification to have at least
threshold (where threshold comes from the trusted current root) number
of keys signing the new root, which were also part of the current
trusted root.
In order to achieve this Lukas suggested that if a key is loaded once
and added to the signing_keys dict, then we shouldn't remove it from
there even if a user wants to remove that key.
This will give us the guarantee that this requirement is met.

This change leads to simplification in that we can use keyids to the
signing_keys instead of key names and this removed the need for the
"_get_rstuf_key_name()" function.

Also, one use case was removed from test_metadata_update where there
are the above threshold requirement is not met as it's practically
impossible to happen now.
Still, I left the exception handling of a possible
"UnsignedMetadataError" error to make sure if there is a problem with
this requirement would have a meaningful message for us.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Address multiple comments

I addressed multiple comments in this commit.

First, "_create_keys_table()" no longer requires "root_info" to be
passed as it's a strange to require that.

Second, I added the "deleted" flag for RSTUFKey objects. This allows
to mark keys as deleted and not show them to the user.

Third, I focused on fixing a problem with how we present the keys
information in "_keys_additions()".
There are 3 things we do now:
1. we will tell the user the new root threshold
2. we are showing all of the new root keys to the user
3. we are printing the number of keys required to be added to complete
the threshold requirement

The problem is that not all keys existing in the new root will be used
for signing. This leads to two questions:
1. how do we calculate if the threshold requirement is met
2. how do we explain to the user that some of the keys we are printing
will be used for signing and others will not
3. how do we explain to the user why he does need to add X number of
keys if already has Y number of keys where Y is higher than the
threshold

The solution that I chose was to utilize the signing_keys dictionary,
not mention anything about the threshold, but instead, focus on a number
of keys needed and when I won't show all of the keys, but only those
used for signing (with a proper message before that).
This way we are showing real information about how many keys are needed
to be added, we show only signing keys without the need for any
explanation.

Finally, to make sure that no deleted keys will be shown to the user
I don't use directly the signing_keys dictionary, but I filter it by
removing all keys that were previously marked with the flag "deleted".

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Update requirements as required

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Remove the "deleted" flag in RSTUFKey class

I realized that we can replace that with a check if the keys exist in
the new root.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Fix requirements failing

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Don't repeat "Failed" twice on an error

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

* Fix two bugs regarding the threshold requirement

There are two bugs I try to address in this pr.

The first bug can be described with a simple example:
Martin can sign root v1, Lukas can sign root v2, and the old and new
threshold is 1 --> As a result root v2 must be signed by both Martin
and Lukas.
The reason is that the old key from the trusted root will be used to
sign the new root version, but it cannot be used to fulfill the
threshold requirement as it's not DEFINED in root v2.

The second bug is that I didn't use keys from trusted root that were
removed for signing. This lead to a situation where the requirement
for a threshold number of keys from the old trusted root signing the
new root is not fulfilled.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>

---------

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>
Signed-off-by: Kairo de Araujo <kdearaujo@vmware.com>
Co-authored-by: Kairo de Araujo <kdearaujo@vmware.com>