Fix import problems
When trying to run any of the modules in repository_service_tuf/helpers
I got this error:

"ImportError: cannot import name 'URL' from partially initialized module
'repository_service_tuf.helpers.api_client'
(most likely due to a circular import) (
repository_service_tuf/helpers/api_client.py)"

This problem comes from loading all modules when importing
repository_service_tuf/cli/__init__.py which loads all modules creating
a circular import.
The fix is to not import anything in the helper modules from
'repository_service_tuf/cli/__init__.py'.

Signed-off-by: Martin Vrachev <mvrachev@vmware.com>