Add regression check for the PR fix
This commit adds the regression verification for overwriting the
`settings.SERVER`.

In case of regression, it raises this error

```
        # test regression https://github.com/vmware/repository-service-tuf-cli/pull/259  # noqa
>       assert test_context["settings"].SERVER is not None
E       assert None is not None
E        +  where None = <dynaconf.base.LazySettings object at 0x10e08f0a0>.SERVER

tests/unit/cli/admin/test_ceremony.py:739: AssertionError
```

Signed-off-by: Kairo de Araujo <kdearaujo@vmware.com>