fix: option --no-auth breaking --upload with auth (#259)
* fix: option --no-auth breaking --upload with auth

This fixes the logic behind `--no-auth` and `--upload` requiring
`--upload-server`.

When the user doesn't use `--no-auth`, but uses `--upload` the current
logic was overwitting the server defined by `rstuf admin login`.

Added tests to prevent regression

Signed-off-by: Kairo de Araujo <kdearaujo@vmware.com>

* Update guide documentation

Update guide documenation including the ``--no-auth`` option

Signed-off-by: Kairo de Araujo <kdearaujo@vmware.com>

* Add regression check for the PR fix

This commit adds the regression verification for overwriting the
`settings.SERVER`.

In case of regression, it raises this error

```
        # test regression https://github.com/vmware/repository-service-tuf-cli/pull/259  # noqa
>       assert test_context["settings"].SERVER is not None
E       assert None is not None
E        +  where None = <dynaconf.base.LazySettings object at 0x10e08f0a0>.SERVER

tests/unit/cli/admin/test_ceremony.py:739: AssertionError
```

Signed-off-by: Kairo de Araujo <kdearaujo@vmware.com>

---------

Signed-off-by: Kairo de Araujo <kdearaujo@vmware.com>